CREATE SEQUENCE ORDERLISTSEQ;

CREATE TABLE ORDERLIST(
ORDER_SEQ NUMBER PRIMARY KEY,
SHOP_SEQ NUMBER REFERENCES SHOP(SHOP_SEQ),
MEMBER_ID VARCHAR2(100) REFERENCES MEMBER(MEMBER_ID),
ORDER_STUFF VARCHAR2(100) NOT NULL,
ORDER_REGDATE DATE NOT NULL,
ORDER_CONTENT VARCHAR2(500), 
ORDER_COUNT NUMBER,
ORDER_BUYMONEY NUMBER
);

DROP TABLE ORDERLIST;

SELECT * FROM ORDERLIST;

INSERT INTO ORDERLIST VALUES(ORDERLISTSEQ.NEXTVAL,2,'3','TEST',SYSDATE,'Z',1,1);