DROP SEQUENCE BOARD_SEQSEQ;
DROP SEQUENCE BOARD_REGROUPSEQ;--답변그룹
DROP TABLE BOARD;

CREATE SEQUENCE BOARD_SEQSEQ;			
CREATE SEQUENCE BOARD_REGROUPSEQ;			


CREATE TABLE BOARD(
	BOARD_SEQ NUMBER PRIMARY KEY,
	MEMBER_NICKNAME VARCHAR2(30) NOT NULL,
	BOARD_TITLE VARCHAR2(500) NOT NULL,
	BOARD_CONTENT VARCHAR2(4000) NOT NULL,
	BOARD_REGDATE DATE NOT NULL,
	BOARD_REGROUP NUMBER NOT NULL,--답변그룹
	BOARD_RESTEP NUMBER NOT NULL, --답변순서
	BOARD_TITLETAB NUMBER NOT NULL,
	BOARD_DELFLAG VARCHAR2(100) NOT NULL,
	BOARD_VIEWS NUMBER NOT NULL,
	CONSTRAINT BO_BD_CHK CHECK (BOARD_DELFLAG IN('Y', 'N')),
	FOREIGN KEY(MEMBER_NICKNAME) REFERENCES MEMBER(MEMBER_NICKNAME)
);

SELECT * FROM BOARD;
SELECT * FROM BOARD ORDER BY BOARD_REGROUP DESC, BOARD_RESTEP;

-- 첫번째 글 작성
INSERT INTO BOARD
VALUES(BOARD_SEQSEQ.NEXTVAL, 'member_nickname01','1번글 입니다.','1번글 내용입니다.',SYSDATE,
       BOARD_REGROUPSEQ.NEXTVAL,1,0,'N',0);

--두번째 글 작성
INSERT INTO BOARD
VALUES(BOARD_SEQSEQ.NEXTVAL, 'member_nickname02','2번글 입니다.','2번글 내용입니다.',SYSDATE,
       BOARD_REGROUPSEQ.NEXTVAL,1,0,'N',0);
--<1>
--1번글입니다(글번호 1번) 에 답변 달기
--UPDATE : 부모의 글과 같은 그룹번호, 부모의 그룹순서보다 더 큰 그룹순서
--         그룹순서를 + 1
UPDATE BOARD
SET BOARD_RESTEP = BOARD_RESTEP + 1
WHERE BOARD_REGROUP = (SELECT BOARD_REGROUP FROM BOARD WHERE BOARD_SEQ = 1)
AND BOARD_RESTEP > (SELECT BOARD_RESTEP FROM BOARD WHERE BOARD_SEQ = 1);


--INSERT boardno3.
INSERT INTO BOARD
VALUES(
	BOARD_SEQSEQ.NEXTVAL,'member_nickname03','RE:1번글 입니다','1번글에 답변달기',SYSDATE,
	(SELECT BOARD_REGROUP FROM BOARD WHERE BOARD_SEQ = 1),
	(SELECT BOARD_RESTEP FROM BOARD WHERE BOARD_SEQ = 1) + 1,
	(SELECT BOARD_TITLETAB FROM BOARD WHERE BOARD_SEQ = 1) + 1,
	 'N',0);
	
--조회수증가
UPDATE BOARD
SET BOARD_VIEWS = BOARD_VIEWS + 1
WHERE BOARD_SEQ =1;
