DROP TABLE MEMBER;

CREATE TABLE MEMBER(
	MEMBER_ID VARCHAR2(50) PRIMARY KEY,
	MEMBER_PW VARCHAR2(50) NOT NULL,
	MEMBER_NAME VARCHAR2(50) NOT NULL,
	MEMBER_BIRTH NUMBER NOT NULL,
	MEMBER_EMAIL VARCHAR2(50) NOT NULL,
	MEMBER_GENDER VARCHAR2(2) NOT NULL,
	MEMBER_ADDRESS VARCHAR2(100) NOT NULL,
	MEMBER_ROLE VARCHAR2(20) NOT NULL,
	MEMBER_DELFLAG VARCHAR2(2) NOT NULL,
	MEMBER_REGDATE DATE NOT NULL,
	MEMBER_PHONE VARCHAR2(20) NOT NULL,
	MEMBER_NICKNAME VARCHAR2(50) NOT NULL,
	CONSTRAINT MM_DEL_CK CHECK(MEMBER_DELFLAG IN('Y','N'))
	
);
	   SELECT * FROM MEMBER WHERE MEMBER_EMAIL = '5';
	   SELECT MEMBER_PW FROM MEMBER WHERE MEMBER_ID = 'y0woo9728' AND MEMBER_EMAIL = 'y0woo9728@nate.com';
	   SELECT MEMBER_ID FROM MEMBER WHERE MEMBER_EMAIL = 'y0woo9728@nate.com';
	   update MEMBER set MEMBER_PW = '1234' WHERE MEMBER_ID = 'y0woo9728';
UPDATE MEMBER SET MEMBER_ROLE = 'CENTER' WHERE MEMBER_ID = '11';
INSERT INTO MEMBER VALUES('ADMIN', '1234', '관리자', '920325', 'zerg_kid@naver.com', 'M', '경기도 수원시 권선구 탑동', 'ADMIN', 'N', SYSDATE, '010-1234-5678', '관리자');
INSERT INTO MEMBER VALUES('TEST', 'TEST', 'TEST', '200228', 'test@naver.com', 'F', '서울시 강남구 역삼동', 'USER', 'N', SYSDATE, '010-9876-5432', 'TEST');

INSERT INTO MEMBER VALUES('TEST5', 'TEST5', 'TEST5', '200228', 'test@naver.com', 'F', '서울시 강남구 역삼동', 'USER', 'N', SYSDATE, '010-9876-5432', 'TEST5');
UPDATE MEMBER SET MEMBER_PW = '1234'
SELECT * FROM MEMBER;
	


SELECT MEMBER_ID,MEMBER_PW,MEMBER_NAME,MEMBER_BIRTH,MEMBER_EMAIL,MEMBER_GENDER,MEMBER_ADDRESS,MEMBER_ROLE,MEMBER_DELFLAG,MEMBER_REGDATE,MEMBER_PHONE,MEMBER_NICKNAME FROM MEMBER WHERE MEMBER_ID = 'ADMIN' AND MEMBER_PW = '1234'

