var LOCALIZE = function(){ return {
'getCurrency' : function(){ return 'KRW'; },
'getCurrencyChar' : function(){ return '₩'; },
'getCurrencyDecimalCount' : function(){ return 0; },
'getCurrencyDecimalChar' : function(){ return '.'; },
'getCurrencyThousandChar' : function(){ return ','; },
'getCurrencyFormat' : function(price){ var _format_string = '%s원'; return _format_string.replace('%s', money_format(price,0,'.',',')); }, 

		'convArguments' : function(){ 
			var msg=arguments[0];
			if (arguments[1].length>0){
				// REQUEST IN getLocalizeString
				if(arguments[1].length === 1 && typeof arguments[1][0] === 'object'){
					for(var i=1; i<=arguments[1][0].length; i++){
						msg = replaceAll(msg, '%'+i, arguments[1][0][i-1]);
					}
				}else{
					for(var i=1; i<=arguments[1].length; i++){
						msg = replaceAll(msg, '%'+i, arguments[1][i-1]);
					}
				}
			}; 
			return msg; 
		},
'설명_비회원예약안내' : function(){ return LOCALIZE.convArguments("비회원인 경우 예약번호(%1)와 예약자의 연락처번호(%2)로 예약조회가 가능합니다. 꼭 숙지하세요", arguments); },
'타이틀_수량' : function(){ return LOCALIZE.convArguments("수량", arguments); },
'설명_장바구니가비어있습니다' : function(){ return LOCALIZE.convArguments("장바구니가 비어있습니다.", arguments); },
'설명_정상적으로접수되었습니다' : function(){ return LOCALIZE.convArguments("정상적으로 접수되었습니다", arguments); },
'버튼_응답수정' : function(){ return LOCALIZE.convArguments("응답 수정", arguments); },
'설명_선택한항목이없습니다' : function(){ return LOCALIZE.convArguments("선택한 항목이 없습니다", arguments); },
'설명_작성권한이없습니다' : function(){ return LOCALIZE.convArguments("작성 권한이 없습니다.", arguments); },
'설명_개인정보처리방침에동의하여주시기바랍니다' : function(){ return LOCALIZE.convArguments("개인정보 수집 및 이용에 동의하여 주시기 바랍니다.", arguments); },
'설명_필수항목을입력하여주시기바랍니다' : function(){ return LOCALIZE.convArguments("필수 항목을 입력하여 주시기 바랍니다.", arguments); },
'버튼_더보기' : function(){ return LOCALIZE.convArguments("더보기", arguments); },
'설명_권한이_없습니다' : function(){ return LOCALIZE.convArguments("권한이 없습니다.", arguments); },
'설명_로그인이_필요합니다' : function(){ return LOCALIZE.convArguments("로그인이 필요합니다.", arguments); },
'설명_내용을_입력해주세요' : function(){ return LOCALIZE.convArguments("내용을 입력해주세요", arguments); },
'설명_삭제된_댓글_입니다' : function(){ return LOCALIZE.convArguments("삭제된 댓글 입니다.", arguments); },
'설명_비밀번호' : function(){ return LOCALIZE.convArguments("비밀번호", arguments); },
'설명_가입승인이_필요한_서비스입니다' : function(){ return LOCALIZE.convArguments("가입승인이 필요한 서비스입니다.", arguments); },
'타이틀_총수량' : function(){ return LOCALIZE.convArguments("총수량 <em class=\"text-brand\">%1</em>개", arguments); },
'버튼_확인닫기' : function(){ return LOCALIZE.convArguments("확인", arguments); },
'타이틀_총금액' : function(){ return LOCALIZE.convArguments("총금액", arguments); },
'설명_이미선택된옵션입니다' : function(){ return LOCALIZE.convArguments("이미 선택된 옵션입니다", arguments); },
'설명_택배사또는송장번호가입력되지않았습니다' : function(){ return LOCALIZE.convArguments("택배사 또는 송장번호가 입력되지 않았습니다.", arguments); },
'설명_택배사배송정보가업데이트중이거나정보가정확하지않습니다' : function(){ return LOCALIZE.convArguments("택배사 배송정보가 업데이트 중이거나 정보가 정확하지 않습니다.", arguments); },
'버튼_메뉴더보기' : function(){ return LOCALIZE.convArguments("더보기", arguments); },
'설명_잘못된접근입니다' : function(){ return LOCALIZE.convArguments("잘못된 접근입니다.", arguments); },
'설명_필수옵션이모두선택되어있지않습니다' : function(){ return LOCALIZE.convArguments("필수옵션이 모두 선택되어있지 않습니다.", arguments); },
'버튼_카카오톡' : function(){ return LOCALIZE.convArguments("카카오톡", arguments); },
'버튼_카카오스토리' : function(){ return LOCALIZE.convArguments("카카오스토리", arguments); },
'버튼_라인' : function(){ return LOCALIZE.convArguments("라인", arguments); },
'버튼_밴드' : function(){ return LOCALIZE.convArguments("밴드", arguments); },
'버튼_페이스북' : function(){ return LOCALIZE.convArguments("페이스북", arguments); },
'버튼_트위터' : function(){ return LOCALIZE.convArguments("트위터", arguments); },
'버튼_인스타그램' : function(){ return LOCALIZE.convArguments("인스타그램", arguments); },
'버튼_공유하기' : function(){ return LOCALIZE.convArguments("공유하기", arguments); },
'설명_카카오톡공유는모바일에서만지원합니다' : function(){ return LOCALIZE.convArguments("카카오톡 공유는 모바일에서만 지원합니다.", arguments); },
'설명_라인공유는모바일에서만지원합니다' : function(){ return LOCALIZE.convArguments("라인공유는 모바일에서만 지원합니다.", arguments); },
'버튼_확인' : function(){ return LOCALIZE.convArguments("확인", arguments); },
'설명_수량' : function(){ return LOCALIZE.convArguments("수량", arguments); },
'설명_주문자이름을입력해주세요' : function(){ return LOCALIZE.convArguments("주문자 이름을 입력해주세요", arguments); },
'설명_주문자연락처를입력해주세요' : function(){ return LOCALIZE.convArguments("주문자 연락처를 입력해주세요", arguments); },
'설명_이메일을입력해주세요' : function(){ return LOCALIZE.convArguments("이메일을 입력해주세요", arguments); },
'설명_배송지이름을입력해주세요' : function(){ return LOCALIZE.convArguments("배송정보의 이름을 입력해주세요", arguments); },
'설명_배송지연락처를입력해주세요' : function(){ return LOCALIZE.convArguments("배송정보의 연락처를 입력해주세요", arguments); },
'설명_개인통관고유부호를입력해주세요' : function(){ return LOCALIZE.convArguments("개인통관고유부호를 입력해주세요", arguments); },
'설명_배송지주소를입력해주세요' : function(){ return LOCALIZE.convArguments("배송지 주소를 입력해주세요", arguments); },
'설명_배송지주소City를입력해주세요' : function(){ return LOCALIZE.convArguments("배송지 주소 (City) 를 입력해주세요", arguments); },
'설명_배송지주소State를입력해주세요' : function(){ return LOCALIZE.convArguments("배송지 주소 (State) 를 입력해주세요", arguments); },
'설명_배송지주소Building를입력해주세요' : function(){ return LOCALIZE.convArguments("배송지 주소 (Building) 를 입력해주세요", arguments); },
'설명_배송지주소Street를입력해주세요' : function(){ return LOCALIZE.convArguments("배송지 주소 (Street) 를 입력해주세요", arguments); },
'설명_배송지주소ZipCode를입력해주세요' : function(){ return LOCALIZE.convArguments("배송지 주소 (Zip Code)를 입력해주세요", arguments); },
'타이틀_취소환불규정에대한동의를해주세요' : function(){ return LOCALIZE.convArguments("취소/환불 규정에 대한 동의를 해주세요.", arguments); },
'설명_가입되어있지않습니다' : function(){ return LOCALIZE.convArguments("가입되어 있지 않습니다", arguments); },
'설명_생성된그룹이없습니다' : function(){ return LOCALIZE.convArguments("생성된 그룹이 없습니다", arguments); },
'설명_거리순정렬이지원되지않습니다' : function(){ return LOCALIZE.convArguments("거리순 정렬이 지원되지 않습니다.", arguments); },
'버튼_상세보기' : function(){ return LOCALIZE.convArguments("상세보기", arguments); },
'설명_비밀번호변경이완료되었습니다' : function(){ return LOCALIZE.convArguments("비밀번호 변경이 완료되었습니다", arguments); },
'설명_동일한암호로입력하시기바랍니다' : function(){ return LOCALIZE.convArguments("동일한 암호로 입력하시기 바랍니다.", arguments); },
'설명_정상적인암호로입력하시기바랍니다' : function(){ return LOCALIZE.convArguments("정상적인 암호로 입력하시기 바랍니다.(4자이상)", arguments); },
'설명_변경가능시간을초과하였습니다' : function(){ return LOCALIZE.convArguments("변경 가능 시간을 초과 하였습니다.", arguments); },
'설명_동의해주세요' : function(){ return LOCALIZE.convArguments("이용약관 및 개인정보 처리방침에 동의하셔야 가입이 가능합니다.", arguments); },
'설명_주소를입력하세요' : function(){ return LOCALIZE.convArguments("주소를 입력하세요", arguments); },
'설명_이미신청중입니다잠시후다시시도하여주시기바랍니다' : function(){ return LOCALIZE.convArguments("이미 신청중입니다. 잠시후 다시 시도하여 주시기 바랍니다.", arguments); },
'설명_올바른전화번호를입력하세요' : function(){ return LOCALIZE.convArguments("올바른 전화번호를 입력하세요", arguments); },
'설명_가입승인이필요합니다' : function(){ return LOCALIZE.convArguments("가입승인이 필요합니다.", arguments); },
'설명_비밀글입니다' : function(){ return LOCALIZE.convArguments("비밀글입니다.", arguments); },
'설명_주소장소를검색해주세요' : function(){ return LOCALIZE.convArguments("주소, 장소를 검색 해주세요.", arguments); },
'설명_주소검색버튼을눌러주세요' : function(){ return LOCALIZE.convArguments("주소검색 버튼을 눌러서 등록해 주세요.", arguments); },
'설명_검색결과가존재하지않습니다' : function(){ return LOCALIZE.convArguments("검색 결과가 존재하지 않습니다.", arguments); },
'설명_삭제하시겠습니까' : function(){ return LOCALIZE.convArguments("삭제하시겠습니까?", arguments); },
'설명_위치정보검색에문제가있습니다' : function(){ return LOCALIZE.convArguments("위치정보 검색에 문제가 있습니다.", arguments); },
'설명_위치정보검색을허용해주세요' : function(){ return LOCALIZE.convArguments("위치정보 검색을 허용해주세요.", arguments); },
'설명_위치정보를검색하지못했습니다' : function(){ return LOCALIZE.convArguments("위치정보를 검색하지 못했습니다.위치정보 수집기능을 작동시켜주세요", arguments); },
'설명_위치정보검색시간을초과하였습니다' : function(){ return LOCALIZE.convArguments("위치정보 검색 시간을 초과하였습니다.", arguments); },
'설명_위치검색이지원되지않는브라우져입니다' : function(){ return LOCALIZE.convArguments("위치검색이 지원되지 않는 브라우져입니다.", arguments); },
'설명_작성시등록하신비밀번호를입력해주세요' : function(){ return LOCALIZE.convArguments("작성시 등록하신 비밀번호를 입력해주세요.", arguments); },
'설명_테스트결제메시지' : function(){ return LOCALIZE.convArguments("현재 테스트 결제 상태입니다.\n테스트 결제에서는 주문하더라도 실제 과금되지 않으며 실제 주문되진 않습니다.", arguments); },
'설명_접근권한이없습니다' : function(){ return LOCALIZE.convArguments("접근 권한이 없습니다", arguments); },
'설명_최대업로드용량안내' : function(){ return LOCALIZE.convArguments("최대 50MB 까지 업로드 하실 수 있습니다.", arguments); },
'설명_네이버페이찜등록실패' : function(){ return LOCALIZE.convArguments("네이버페이 찜등록 실패 (%1)", arguments); },
'설명_네이버페이상품구매실패' : function(){ return LOCALIZE.convArguments("아직 네이버페이 심사가 진행중(ERR-OR-000001)이거나 연동 오류입니다. (%1)", arguments); },
'설명_성공' : function(){ return LOCALIZE.convArguments("성공", arguments); },
'설명_취소되었습니다' : function(){ return LOCALIZE.convArguments("취소 되었습니다.", arguments); },
'설명_취소요청이접수되었습니다' : function(){ return LOCALIZE.convArguments("취소요청이 접수 되었습니다.", arguments); },
'타이틀_대표이미지설정' : function(){ return LOCALIZE.convArguments("대표 이미지 설정", arguments); },
'설명_첨부된이미지가없습니다' : function(){ return LOCALIZE.convArguments("첨부된 이미지가 없습니다.", arguments); },
'설명_최대업로드용량안내_게시판' : function(){ return LOCALIZE.convArguments("최대 100MB 까지 업로드 하실 수 있습니다.", arguments); },
'설명_오전' : function(){ return LOCALIZE.convArguments("오전", arguments); },
'설명_오후' : function(){ return LOCALIZE.convArguments("오후", arguments); },
'설명_페이지를벗어나시겠습니까' : function(){ return LOCALIZE.convArguments("이 페이지를 벗어나시겠습니까?", arguments); },
'설명_테스트결제메시지_이니시스' : function(){ return LOCALIZE.convArguments("현재 테스트 결제 상태입니다.\nKG 이니시스의 경우엔 주문 하신 후 일정시간이 지나면 자동으로 취소 처리가 됩니다.", arguments); },
'설명_주문하실상품을선택해주세요' : function(){ return LOCALIZE.convArguments("주문하실 상품을 선택해 주세요.", arguments); },
'버튼_네이버' : function(){ return LOCALIZE.convArguments("네이버", arguments); },
'설명_네이버페이를계속해서진행하시겠습니까' : function(){ return LOCALIZE.convArguments("N페이 결제를 계속해서 진행하시겠습니까?", arguments); },
'설명_작성하신대로접수하시겠습니까' : function(){ return LOCALIZE.convArguments("작성하신대로 접수하시겠습니까?", arguments); },
'설명_최소이미지크기안내' : function(){ return LOCALIZE.convArguments("%1x%2 이상의 이미지만 업로드 하실 수 있습니다.", arguments); },
'버튼_파일첨부_최대nMB' : function(){ return LOCALIZE.convArguments("파일첨부(최대 %1MB)", arguments); },
'설명_이미지업로드URL이비어있습니다' : function(){ return LOCALIZE.convArguments("이미지 업로드 URL이 비어있습니다.", arguments); },
'설명_파일업로드URL이비어있습니다' : function(){ return LOCALIZE.convArguments("파일 업로드 URL이 비어있습니다.", arguments); },
'설명_파일리스트를확인하세요' : function(){ return LOCALIZE.convArguments("파일 리스트를 확인하세요.", arguments); },
'설명_드래그업로드는지원하지않습니다' : function(){ return LOCALIZE.convArguments("드래그 업로드는 지원하지 않습니다.", arguments); },
'설명_이미지복사붙여넣기기능은지원하지않습니다' : function(){ return LOCALIZE.convArguments("이미지 복사 붙여넣기 기능은 지원하지 않습니다.", arguments); },
'버튼_가로구분선만' : function(){ return LOCALIZE.convArguments("가로 구분선만", arguments); },
'버튼_테두리없음' : function(){ return LOCALIZE.convArguments("테두리 없음", arguments); },
'버튼_테두리진하게' : function(){ return LOCALIZE.convArguments("테두리 진하게", arguments); },
'버튼_Hover효과행단위' : function(){ return LOCALIZE.convArguments("Hover 효과(행 단위)", arguments); },
'버튼_테이블헤더음영' : function(){ return LOCALIZE.convArguments("테이블 헤더 음영", arguments); },
'버튼_줄무늬행' : function(){ return LOCALIZE.convArguments("줄무늬 행", arguments); },
'버튼_모바일에서표형식무시' : function(){ return LOCALIZE.convArguments("모바일에서 표 형식 무시", arguments); },
'버튼_반응형테이블' : function(){ return LOCALIZE.convArguments("반응형 테이블", arguments); },
'버튼_기본버튼' : function(){ return LOCALIZE.convArguments("기본 버튼", arguments); },
'버튼_강조버튼' : function(){ return LOCALIZE.convArguments("강조 버튼", arguments); },
'설명_사이트관리자설정에의해차단된콘텐츠입니다' : function(){ return LOCALIZE.convArguments("사이트 관리자 설정에 의해 차단된 콘텐츠입니다.", arguments); },
'타이틀_주문취소를진행하시겠습니까' : function(){ return LOCALIZE.convArguments("주문 취소를 진행하시겠습니까?", arguments); },
'타이틀_예약취소를진행하시겠습니까' : function(){ return LOCALIZE.convArguments("예약 취소를 진행하시겠습니까?", arguments); },
'타이틀_글쓰기카테고리선택' : function(){ return LOCALIZE.convArguments("카테고리", arguments); },
'설명_신고가성공적으로접수되었습니다' : function(){ return LOCALIZE.convArguments("신고가 성공적으로 접수되었습니다.", arguments); },
'버튼_복사' : function(){ return LOCALIZE.convArguments("복사", arguments); },
'설명_URL을길게누르면복사할수있습니다' : function(){ return LOCALIZE.convArguments("URL을 길게 누르면 복사 할 수 있습니다.", arguments); },
'설명_URL이복사되었습니다' : function(){ return LOCALIZE.convArguments("URL이 복사되었습니다.", arguments); },
'설명_개인정보제3자제공에동의하여주시기바랍니다' : function(){ return LOCALIZE.convArguments("개인정보 제 3자 제공에 동의하여 주시기 바랍니다.", arguments); },
'설명_숨기시겠습니까' : function(){ return LOCALIZE.convArguments("숨기시겠습니까?", arguments); },
'설명_최대n개까지선택가능합니다' : function(){ return LOCALIZE.convArguments("최대 %1개까지 선택 가능합니다.", arguments); },
'설명_macOS에서ISP결제' : function(){ return LOCALIZE.convArguments("macOS에서는 ISP결제(KB국민, BC, 우리, 저축은행, 전북, 수협, 제주 카드)를 지원하지 않습니다. \n해당 카드로 결제하시려면 모바일로 결제해 주시기 바랍니다.", arguments); },
'설명_최대N개만구매가능한상품입니다' : function(){ return LOCALIZE.convArguments("최대 %1개만 구매 가능한 상품입니다.", arguments); },
'설명_장소를수정할수없습니다' : function(){ return LOCALIZE.convArguments("장소를 수정할 수 없습니다.", arguments); },
'설명_도로명지번을검색해주세요' : function(){ return LOCALIZE.convArguments("도로명 주소 또는 지번 주소를 검색 해주세요.", arguments); },
'설명_최대이미지크기안내' : function(){ return LOCALIZE.convArguments("%1x%2 이하의 이미지만 업로드 하실 수 있습니다.", arguments); },
'설명_삭제하시겠습니까삭제후재등록불가' : function(){ return LOCALIZE.convArguments("해당 구매평을 삭제하시겠습니까? \n(삭제 후 재등록은 불가능합니다.)", arguments); },
'설명_공유에실패하였습니다' : function(){ return LOCALIZE.convArguments("공유에 실패하였습니다.", arguments); },
'설명_디지털상품은수량을변경하실수없습니다' : function(){ return LOCALIZE.convArguments("디지털 상품은 수량을 변경하실 수 없습니다.", arguments); },
'설명_해당선택옵션은최대N개까지구매가능합니다' : function(){ return LOCALIZE.convArguments("해당 선택옵션은 최대 %1개까지 구매 가능합니다.", arguments); },
'설명_0원상품갯수제한' : function(){ return LOCALIZE.convArguments("해당 선택옵션은 상품 구매 수량 만큼 구매 가능합니다. \n(예: 본상품 5개 구매시 해당 선택 옵션은 5개까지 구매 가능)", arguments); },
'설명_현재재고부족으로N개이상구매할수없습니다' : function(){ return LOCALIZE.convArguments("현재 재고 부족으로 %1개 이상 구매할 수 없습니다.", arguments); },
'타이틀_회원할인금액' : function(){ return LOCALIZE.convArguments("회원 할인 금액", arguments); },
'타이틀_s회원가' : function(){ return LOCALIZE.convArguments("%1 회원가", arguments); },
'설명_기기의위치정보검색실패' : function(){ return LOCALIZE.convArguments("기기의 위치정보 검색에 실패 했습니다. 위치수집 설정을 확인해주세요.", arguments); },
'설명_회원등급할인' : function(){ return LOCALIZE.convArguments("회원등급 할인", arguments); },
'설명_결제예상금액' : function(){ return LOCALIZE.convArguments("총 상품금액(%1개)", arguments); },
'설명_가입승인되지않은아이디입니다' : function(){ return LOCALIZE.convArguments("가입승인 대기 중입니다. 운영자의 승인 후 이용하실 수 있습니다.", arguments); },
'설명_인증메일발송완료' : function(){ return LOCALIZE.convArguments("인증메일을 발송하였습니다.", arguments); },
'설명_구매가능회원이아닙니다' : function(){ return LOCALIZE.convArguments("구매 가능 회원이 아닙니다.", arguments); },
'타이틀_PC모드로보기' : function(){ return LOCALIZE.convArguments("PC 모드로 보기", arguments); },
'타이틀_모바일모드로보기' : function(){ return LOCALIZE.convArguments("모바일 모드로 보기", arguments); },
'설명_해당옵션필수입니다' : function(){ return LOCALIZE.convArguments("해당 옵션은 필수입니다.", arguments); },
'설명_즐겨찾기등록키안내' : function(){ return LOCALIZE.convArguments("%1 키를 눌러 즐겨찾기에 등록하실 수 있습니다.", arguments); },
'설명_수취인이름을n글자이상입력해주세요' : function(){ return LOCALIZE.convArguments("배송지 정보의 수취인 이름을 %1 글자 이상 입력해 주세요", arguments); },
'설명_인증번호를입력해주세요' : function(){ return LOCALIZE.convArguments("인증번호를 입력해주세요", arguments); },
'설명_인증이완료되었습니다' : function(){ return LOCALIZE.convArguments("인증이 완료되었습니다.", arguments); },
'설명_비밀번호재설정링크유효기간만료' : function(){ return LOCALIZE.convArguments("비밀번호 재설정 링크 유효기간이 만료되었습니다. 내 계정 찾기를 이용해주세요.", arguments); },

}}();