
CREATE SEQUENCE VOLUNTEER_SEQUENCE;


CREATE TABLE VOLUNTEER(
VOLUNTEER_SEQ NUMBER PRIMARY KEY,
MEMBER_ID VARCHAR2(400) REFERENCES MEMBER(MEMBER_ID),
VOLUNTEER_TITLE VARCHAR2(300) NOT NULL,
VOLUNTEER_CONTENT VARCHAR2(1000) NOT NULL,
VOLUNTEER_MAXVOLUNTEER NUMBER NOT NULL,
VOLUNTEER_NOWVOLUNTEER NUMBER,
VOLUNTEER_DATE VARCHAR2(30) NOT NULL
);

CREATE TABLE APPLY(
APPLY_SEQ NUMBER PRIMARY KEY,
VOLUNTEER_SEQ NUMBER REFERENCES VOLUNTEER(VOLUNTEER_SEQ),
MEMBER_ID VARCHAR2(400) REFERENCES MEMBER(MEMBER_ID),
APPLY_PHONE VARCHAR2(300) NOT NULL,
APPLY_NAME VARCHAR2(300) NOT NULL,
APLLY_EMAIL VARCHAR2(300) NOT NULL
);

SELECT * FROM VOLUNTEER;

DELETE FROM VOLUNTEER WHERE VOLUNTEER_SEQ = 4;

insert into volunteer values ('ADMIN', '적당히해', '알겠냐?', '20190101', 1, sysdate);