

CREATE SEQUENCE CENTERSEQ;

CREATE TABLE CENTER(
CENTER_SEQ NUMBER PRIMARY KEY,
MEMBER_ID VARCHAR2(400) REFERENCES MEMBER(MEMBER_ID),
CENTER_NAME VARCHAR2(100) NOT NULL,
CENTER_ADDR VARCHAR2(400) NOT NULL,
CENTER_PHONE VARCHAR2(20) NOT NULL,
CENTER_LATITUDE VARCHAR2(100),
CENTER_LONGITUDE VARCHAR2(100)
);

SELECT * FROM CENTER;
